name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        git config --list
      env:
        test_value: yo!!!
